export const LEFT_SIDEBAR_SHOW = 'LEFT_SIDEBAR_SHOW'
export const LEFT_SIDEBAR_HIDE = 'LEFT_SIDEBAR_HIDE'

export const UNVERIFYED_USER_ADD = 'UNVERIFYED_USER_ADD'
export const VERIFYED_USER_ADD = 'VERIFYED_USER_ADD'

//Thunk constants

export const SET_THUNK_REQUEST_REGISTERED_USERS = 'SET_THUNK_REQUEST_REGISTERED_USERS'
export const VIDEO_PREVIEWS_THUNK = 'VIDEO_PREVIEWS_THUNK'
export const COMMENTS_VIDEO_THUNK = 'COMMENTS_VIDEO_THUNK'
export const USERS_DICTIONARY = 'USERS_DICTIONARY'
export const GET_VIDEO = 'GET_VIDEO'
export const ERROR_API_PROCESSING = 'ERROR_API_PROCESSING'
export const IS_USER_TOKEN = 'IS_USER_TOKEN'
export const IS_VERIFYED_USER = 'IS_VERIFYED_USER'
export const VIDEO_OWNER_USER = 'VIDEO_OWNER_USER'
